modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="locktfon"
version="${file.jarVersion}"
displayName="LockTFOn"
authors="PIASOP"
description='''Souls-like camera lock-on system'''